/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package academia;

import java.util.ArrayList;
import javax.swing.JTabbedPane;
import javax.swing.JOptionPane;

/**
 *
 * @author duran
 */
public class MenuGrafico extends javax.swing.JFrame {

    /**
     * Creates new form MenuGrafico
     */
    public MenuGrafico() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel12 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        no = new javax.swing.JTextField();
        idade = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        sexo = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        loj = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        botaoMensal = new javax.swing.JRadioButton();
        botaoSemanal = new javax.swing.JRadioButton();
        botaoDiario = new javax.swing.JRadioButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel14 = new javax.swing.JLabel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jInternalFrame2 = new javax.swing.JInternalFrame();
        sucesso = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        consultaNome = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        nome = new javax.swing.JTextField();
        id = new javax.swing.JTextField();
        funcao = new javax.swing.JTextField();
        loja = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        saidaConsulta = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        entradaConsulta = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/academia/academia fundo em miniatura.jpg"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setBackground(new java.awt.Color(87, 33, 59));
        jTabbedPane1.setForeground(new java.awt.Color(73, 93, 99));

        jTabbedPane2.setForeground(new java.awt.Color(87, 33, 59));

        jInternalFrame1.setBackground(new java.awt.Color(255, 255, 198));
        jInternalFrame1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jInternalFrame1.setVisible(true);
        jInternalFrame1.getContentPane().setLayout(null);

        no.setBackground(new java.awt.Color(87, 33, 59));
        no.setBorder(new javax.swing.border.MatteBorder(null));
        no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(no);
        no.setBounds(10, 70, 67, 29);

        idade.setBackground(new java.awt.Color(87, 33, 59));
        idade.setBorder(new javax.swing.border.MatteBorder(null));
        jInternalFrame1.getContentPane().add(idade);
        idade.setBounds(10, 30, 67, 29);
        jInternalFrame1.getContentPane().add(jTextField4);
        jTextField4.setBounds(44, 612, 67, 29);

        jLabel7.setBackground(new java.awt.Color(243, 113, 165));
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("nome");
        jLabel7.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), new javax.swing.border.MatteBorder(null)));
        jInternalFrame1.getContentPane().add(jLabel7);
        jLabel7.setBounds(100, 25, 45, 20);

        jLabel8.setBackground(new java.awt.Color(243, 113, 165));
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("idade");
        jLabel8.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), new javax.swing.border.MatteBorder(null)));
        jInternalFrame1.getContentPane().add(jLabel8);
        jLabel8.setBounds(100, 65, 45, 20);

        jLabel9.setText("loja");
        jInternalFrame1.getContentPane().add(jLabel9);
        jLabel9.setBounds(141, 619, 17, 14);

        sexo.setBackground(new java.awt.Color(87, 33, 59));
        sexo.setBorder(new javax.swing.border.MatteBorder(null));
        sexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sexoActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(sexo);
        sexo.setBounds(10, 110, 67, 29);

        jLabel10.setBackground(new java.awt.Color(243, 113, 165));
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("sexo");
        jLabel10.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), new javax.swing.border.MatteBorder(null)));
        jInternalFrame1.getContentPane().add(jLabel10);
        jLabel10.setBounds(100, 105, 45, 20);

        loj.setBackground(new java.awt.Color(87, 33, 59));
        loj.setBorder(new javax.swing.border.MatteBorder(null));
        loj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lojActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(loj);
        loj.setBounds(10, 150, 67, 29);

        jLabel11.setBackground(new java.awt.Color(243, 113, 165));
        jLabel11.setForeground(new java.awt.Color(87, 33, 59));
        jLabel11.setText("loja");
        jLabel11.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), new javax.swing.border.MatteBorder(null)));
        jInternalFrame1.getContentPane().add(jLabel11);
        jLabel11.setBounds(100, 145, 45, 20);

        jButton9.setBackground(new java.awt.Color(87, 33, 59));
        jButton9.setText("Cadastro");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(jButton9);
        jButton9.setBounds(230, 200, 77, 23);

        botaoMensal.setBackground(new java.awt.Color(152, 182, 177));
        botaoMensal.setForeground(new java.awt.Color(87, 33, 59));
        botaoMensal.setText("Mensal");
        botaoMensal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoMensalActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(botaoMensal);
        botaoMensal.setBounds(262, 44, 59, 23);

        botaoSemanal.setBackground(new java.awt.Color(152, 182, 177));
        botaoSemanal.setForeground(new java.awt.Color(87, 33, 59));
        botaoSemanal.setText("Semanal");
        botaoSemanal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSemanalActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(botaoSemanal);
        botaoSemanal.setBounds(262, 80, 65, 23);

        botaoDiario.setBackground(new java.awt.Color(152, 182, 177));
        botaoDiario.setForeground(new java.awt.Color(87, 33, 59));
        botaoDiario.setText("Diario");
        botaoDiario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoDiarioActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(botaoDiario);
        botaoDiario.setBounds(262, 117, 53, 23);

        jRadioButton1.setBackground(new java.awt.Color(152, 182, 177));
        jRadioButton1.setText("Boleto");
        jInternalFrame1.getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(410, 30, 55, 23);

        jRadioButton2.setBackground(new java.awt.Color(152, 182, 177));
        jRadioButton2.setText("Cartão de Crédito");
        jInternalFrame1.getContentPane().add(jRadioButton2);
        jRadioButton2.setBounds(410, 100, 120, 23);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/academia/academia fundo em miniatura.jpg"))); // NOI18N
        jLabel14.setText("jLabel14");
        jInternalFrame1.getContentPane().add(jLabel14);
        jLabel14.setBounds(0, -10, 610, 450);

        jTabbedPane2.addTab("inserção", jInternalFrame1);
        jTabbedPane2.addTab("", jTabbedPane3);

        jInternalFrame2.setBackground(new java.awt.Color(255, 255, 198));
        jInternalFrame2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jInternalFrame2.setVisible(true);

        sucesso.setBackground(new java.awt.Color(152, 182, 177));
        sucesso.setBorder(new javax.swing.border.MatteBorder(null));

        jButton7.setBackground(new java.awt.Color(152, 182, 177));
        jButton7.setForeground(new java.awt.Color(87, 33, 59));
        jButton7.setText("novo");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setBackground(new java.awt.Color(152, 182, 177));
        jButton8.setForeground(new java.awt.Color(87, 33, 59));
        jButton8.setText("consulta cliente");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrame2Layout = new javax.swing.GroupLayout(jInternalFrame2.getContentPane());
        jInternalFrame2.getContentPane().setLayout(jInternalFrame2Layout);
        jInternalFrame2Layout.setHorizontalGroup(
            jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame2Layout.createSequentialGroup()
                .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(sucesso, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(consultaNome)
                            .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)))
                    .addGroup(jInternalFrame2Layout.createSequentialGroup()
                        .addGap(274, 274, 274)
                        .addComponent(jButton8)))
                .addContainerGap(260, Short.MAX_VALUE))
        );
        jInternalFrame2Layout.setVerticalGroup(
            jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame2Layout.createSequentialGroup()
                .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame2Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jButton7)
                        .addGap(35, 35, 35)
                        .addComponent(jButton8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(consultaNome, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jInternalFrame2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(sucesso, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(309, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("retorno", jInternalFrame2);

        jTabbedPane1.addTab("Clientes", jTabbedPane2);

        jPanel2.setBackground(new java.awt.Color(255, 255, 198));
        jPanel2.setLayout(null);

        nome.setBackground(new java.awt.Color(152, 182, 177));
        nome.setBorder(new javax.swing.border.MatteBorder(null));
        nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeActionPerformed(evt);
            }
        });
        jPanel2.add(nome);
        nome.setBounds(10, 11, 67, 29);

        id.setBackground(new java.awt.Color(152, 182, 177));
        id.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel2.add(id);
        id.setBounds(10, 51, 67, 29);

        funcao.setBackground(new java.awt.Color(152, 182, 177));
        funcao.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel2.add(funcao);
        funcao.setBounds(10, 91, 67, 29);

        loja.setBackground(new java.awt.Color(152, 182, 177));
        loja.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel2.add(loja);
        loja.setBounds(10, 131, 67, 29);

        jButton1.setBackground(new java.awt.Color(152, 182, 177));
        jButton1.setForeground(new java.awt.Color(87, 33, 59));
        jButton1.setText(" gerente");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(480, 60, 119, 28);

        jButton2.setBackground(new java.awt.Color(152, 182, 177));
        jButton2.setForeground(new java.awt.Color(87, 33, 59));
        jButton2.setText("caixa");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(480, 100, 119, 23);

        jButton3.setBackground(new java.awt.Color(152, 182, 177));
        jButton3.setForeground(new java.awt.Color(87, 33, 59));
        jButton3.setText(" instrutores");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3);
        jButton3.setBounds(480, 140, 119, 23);

        jButton4.setBackground(new java.awt.Color(152, 182, 177));
        jButton4.setForeground(new java.awt.Color(87, 33, 59));
        jButton4.setText("colaboradores");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4);
        jButton4.setBounds(480, 180, 119, 23);

        jLabel1.setBackground(new java.awt.Color(152, 182, 177));
        jLabel1.setForeground(new java.awt.Color(87, 33, 59));
        jLabel1.setText("nome");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(jLabel1);
        jLabel1.setBounds(81, 16, 45, 20);

        jLabel2.setBackground(new java.awt.Color(152, 182, 177));
        jLabel2.setForeground(new java.awt.Color(87, 33, 59));
        jLabel2.setText("id");
        jLabel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(jLabel2);
        jLabel2.setBounds(81, 56, 45, 20);

        jLabel3.setBackground(new java.awt.Color(152, 182, 177));
        jLabel3.setForeground(new java.awt.Color(87, 33, 59));
        jLabel3.setText("função");
        jLabel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(jLabel3);
        jLabel3.setBounds(81, 96, 45, 20);

        jLabel4.setBackground(new java.awt.Color(152, 182, 177));
        jLabel4.setForeground(new java.awt.Color(87, 33, 59));
        jLabel4.setText("loja");
        jLabel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(jLabel4);
        jLabel4.setBounds(81, 136, 45, 20);

        jLabel5.setBackground(new java.awt.Color(210, 230, 220));
        jLabel5.setForeground(new java.awt.Color(87, 33, 59));
        jLabel5.setText("Quem você deseja cadastrar");
        jLabel5.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jPanel2.add(jLabel5);
        jLabel5.setBounds(460, 20, 138, 14);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/academia/academia fundo em miniatura.jpg"))); // NOI18N
        jPanel2.add(jLabel13);
        jLabel13.setBounds(0, -30, 610, 470);

        jTabbedPane1.addTab("Colaboradores", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 198));

        saidaConsulta.setBackground(new java.awt.Color(152, 182, 177));
        saidaConsulta.setBorder(new javax.swing.border.MatteBorder(null));

        jButton5.setForeground(new java.awt.Color(87, 33, 59));
        jButton5.setText("consultar funcionario");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        entradaConsulta.setBackground(new java.awt.Color(87, 33, 59));
        entradaConsulta.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel6.setBackground(new java.awt.Color(152, 182, 177));
        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(87, 33, 59));
        jLabel6.setText("Retorno da consulta");
        jLabel6.setBorder(new javax.swing.border.MatteBorder(null));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(saidaConsulta))
                .addGap(40, 40, 40)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(entradaConsulta)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(296, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saidaConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(entradaConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(379, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("retorno", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 657, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 554, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        
        String n = nome.getText();
        String i= id.getText();
        String f= funcao.getText();
        String l= loja.getText();
        Gerente g = new Gerente(n, i, f, l);
        funcionariosGerais.add(g);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String n = nome.getText();
        String i= id.getText();
        String f= funcao.getText();
        String l=loja.getText();
        Caixa c= new Caixa(n,i,f,l);
        funcionariosGerais.add(c);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String n = nome.getText();
        String i= id.getText();
        String f= funcao.getText();
        String l=loja.getText();
        Instrutores ins=new Instrutores(n,i,f,l);
        funcionariosGerais.add(ins);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       String n = nome.getText();
        String i= id.getText();
        String f= funcao.getText();
        String l=loja.getText();
        Colaboradores colab=new Colaboradores(n,i,f,l);
        funcionariosGerais.add(colab);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        boolean encontrou=false;
        String  entrada=entradaConsulta.getText();
        for(Funcionarios i: funcionariosGerais){
            if(i.getNome().equals(entrada)){
                saidaConsulta.setText(i.getFuncao()+" "+"id"+" "+i.getId()+" "+i.getLoja());
                encontrou=true;
            }
            
                
          
        }
        if(!encontrou){
            saidaConsulta.setText("não encontrado!");
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        boolean search=false;
        String  entra = consultaNome.getText();
       // sucesso.setText(clientesgerais.size()+" ");
        for(Clientes j: clientesgerais){
            if(j.getNome().equals(entra)){
                sucesso.setText(j.getSexo()+" "+"sexo"+" "+j.getIdade()+"idade "+j.getLocal());
                
                search=true;
            }

        }
        if(!search){
            sucesso.setText("não encontrado!");
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed

    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
       JOptionPane.showMessageDialog(null,"usuario cadastrado"+" ");
        String n=no.getText();
        String i=idade.getText();
        String s=sexo.getText();
        String l=loj.getText();
        Planos_de_Aulas bol;
        Planos_de_Aulas men;
        Planos_de_Aulas cartao;
        Planos_de_Aulas sem;
        Planos_de_Aulas dia;
        
        if(botaoMensal.isSelected()){
             men= new Mensal();
            if (jRadioButton1.isSelected()){
               
            bol=new Boleto();
            Clientes cli=new Clientes(i,n,s,l,men,bol,null);
            clientesgerais.add(cli);
                }   
            else if(jRadioButton2.isSelected()){
                cartao=new Cartao();
                Clientes cli=new Clientes(n, i, s, l,men,null,cartao);
                clientesgerais.add(cli);
            }
        }
        else if(botaoSemanal.isSelected()){
            sem =new Semanal();
             if (jRadioButton1.isSelected()){
               
            bol=new Boleto();
            Clientes cli=new Clientes(i,n,s,l,sem,bol,null);
            clientesgerais.add(cli);
                }   
            else if(jRadioButton2.isSelected()){
                cartao=new Cartao();
                Clientes cli=new Clientes(n, i, s, l,sem,null,cartao);
                clientesgerais.add(cli);
            }
            
        }
        else if(botaoDiario.isSelected()){
            dia=new Diario();
             if (jRadioButton1.isSelected()){
               
            bol=new Boleto();
            Clientes cli=new Clientes(i,n,s,l,dia,bol,null);
            clientesgerais.add(cli);
                }   
            else if(jRadioButton2.isSelected()){
                cartao=new Cartao();
                Clientes cli=new Clientes(n, i, s, l,dia,null,cartao);
                clientesgerais.add(cli);
            }
        }
        
        

        sucesso.setText(n+i+s+l+"Cadastro realizado com sucesso");
    }//GEN-LAST:event_jButton9ActionPerformed

    private void sexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sexoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sexoActionPerformed

    private void lojActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lojActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lojActionPerformed

    private void botaoMensalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoMensalActionPerformed
      // Mensal m=new Mensal();
       
      // sucesso.setText(m.realizarPagamento() + "pagamento mensal");
    }//GEN-LAST:event_botaoMensalActionPerformed

    private void botaoSemanalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSemanalActionPerformed
       Semanal s=new Semanal();
       s.realizarPagamento();
       sucesso.setText(s.realizarPagamento() + "pagamento semanal");
    }//GEN-LAST:event_botaoSemanalActionPerformed

    private void botaoDiarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoDiarioActionPerformed
       Diario d;
        d = new Diario();
        d.realizarPagamento();
       sucesso.setText(d.realizarPagamento()+"pagamento diaria");
       
    }//GEN-LAST:event_botaoDiarioActionPerformed

    private void noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noActionPerformed
ArrayList<Funcionarios> funcionariosGerais = new ArrayList();
ArrayList<Clientes> clientesgerais = new ArrayList();
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuGrafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuGrafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuGrafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuGrafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuGrafico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton botaoDiario;
    private javax.swing.JRadioButton botaoMensal;
    private javax.swing.JRadioButton botaoSemanal;
    private javax.swing.JTextField consultaNome;
    private javax.swing.JTextField entradaConsulta;
    private javax.swing.JTextField funcao;
    private javax.swing.JTextField id;
    private javax.swing.JTextField idade;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JInternalFrame jInternalFrame2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField loj;
    private javax.swing.JTextField loja;
    private javax.swing.JTextField no;
    private javax.swing.JTextField nome;
    private javax.swing.JTextField saidaConsulta;
    private javax.swing.JTextField sexo;
    private javax.swing.JTextField sucesso;
    // End of variables declaration//GEN-END:variables
}
